import React from 'react';
import axios from 'axios';
import styles from '../../css/mobile/Term.module.css';
import commonstyles from '../../css/mobile/Common.module.css';

class Term extends React.Component{
  state = {
    email : '',
    data : [],
    checkFlag : false,
    checkView : false,
  }  
  render(){
    return (
      <div className={commonstyles.full_width_colume}>
        <div className={styles.terms_container}>
          <div className={styles.terms_title_image}>
            <img className={commonstyles.image_width} src="https://image.soribada.com/image/sobanft/images/mobile/img_m_title_footer_terms.png" />
          </div>
          <hr className={commonstyles.title_line} />
          <div className={styles.terms_content_container}>
            <p className={styles.terms_content_text}>
            These Terms Set Forth a Legally Binding Agreement<br/><br/>

Please read these Terms of Use (“Terms”, “Terms of Use”, or “Agreement”) very carefully. This Agreement is between you (the “User(s),” “Artist(s),” “Collector(s),” “Owner(s),” and collectively with others using the Site - “Users”) and NFT Global Ltd, Inc., a company operating the SOBA platform and organized under the laws of the Seychelles (“NFT Global Ltd.,” “SOBA,” “the Company”, “we”, “our” or “us” and together with you, the “Parties”).  These Terms govern your use of the website located at SOBANFT.COM (the “Site”), and all related tools, mobile applications, web applications, decentralized applications, smart contracts and APIs located at any of NFT Global Ltd websites, including without limitation, successor website(s) or application(s) thereto (the “Platform”).<br/><br/>

THESE TERMS SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SITE OR PLATFORM.  BY ACCESSING OR USING THE SITE, SERVICES, OR SMART CONTRACTS YOU ARE ACCEPTING THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT).  IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS, YOU ARE PROHIBITED FROM ACCESSING, USING, OR TRANSACTING ON THE SITE OR PLATFORM.  YOU FURTHER REPRESENT AND WARRANT THAT YOU ARE OTHERWISE LEGALLY PERMITTED TO USE THE SERVICES IN YOUR JURISDICTION AND THAT THE COMPANY IS NOT LIABLE FOR YOUR COMPLIANCE WITH SUCH APPLICABLE LAWS.<br/><br/>

The Platform<br/>
Accessing the Platform with MetaMask<br/>
To most easily access and use the Platform, you should first install the Google Chrome or Brave web browser.  Once you have installed Chrome or Brave, you will need to install a browser extension called MetaMask.  MetaMask is an electronic wallet, which allows you to purchase, store, and engage in transactions using the native Ethereum cryptocurrency, ETH. You will not be able to engage in any transactions on the Platform other than through MetaMask (or other Ethereum-compatible browsers). The Platform will only recognize you as a User, and you will only be able to interact with the Platform, if your Ethereum electronic wallet is connected and unlocked through your MetaMask account. There is no other way to sign up as a User, or to interact directly with the Platform.<br/>
Transactions Are Recorded on the Public Ethereum Blockchain<br/>
Transactions that take place on the Platform are managed and confirmed via the Ethereum blockchain. The User understands that your Ethereum public address will be made publicly visible whenever you engage in a transaction on the Platform.  We neither own nor control MetaMask, Coinbase, Google Chrome, the Ethereum network, or any other third party site, product, or service that you might access, visit, or use for the purpose of enabling you to use the various features of the Platform. We will not be liable for the acts or omissions of any such third parties, nor will we be liable for any damage that you may suffer as a result of your transactions or any other interaction with any such third parties.<br/><br/>

The Platform Is Property of NFT Global Ltd.,<br/>
You acknowledge and agree that we (or, as applicable, our licensors) own all legal right, title and interest in and to all elements of the Platform.  The graphics, design, systems, methods, information, computer code, software, services, “look and feel”, organization, compilation of the content, code, data, and all other elements of the Platform (collectively, the “SOBA Materials”) are owned by NFT Global Ltd., and are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws.  All SOBA Materials are the copyrighted property of NFT Global Ltd., or its licensors, and all trademarks, service marks, and trade names contained in the SOBA Materials are proprietary to NFT Global Ltd., or its licensors. Except as expressly set forth herein, your use of the Platform does not grant you ownership of or any other rights with respect to any content, code, data, or other materials that you may access on or through the Platform. We reserve all rights in and to the SOBA Materials not expressly granted to you in the Terms.<br/><br/>

NFT Global Ltd., May Use and Share All User Feedback<br/>
You may choose to submit comments, bug reports, ideas or other feedback about the Platform, including without limitation about how to improve the Platform (collectively, “Feedback”). By submitting any Feedback, you agree that we are free to use such Feedback at our discretion and without additional compensation to you, and to disclose such Feedback to third parties (whether on a non-confidential basis, or otherwise). You hereby grant us a perpetual, irrevocable, non-exclusive, worldwide license under all rights necessary for us to incorporate and use your Feedback for any purpose.<br/><br/>

SOBA is a Non-Custodial Service Provider<br/>
The Smart Contracts and the Site facilitate User collection of SOBA Items, but NFT Global Ltd., and its affiliates, the Platform, and the Smart Contracts are not the custodians of any User-owned SOBA Items.  The User understands and acknowledges that the Smart Contracts do not give NFT Global Ltd., custody, possession, or control of any SOBA Item or cryptocurrency at any time for the purpose of facilitating SOBA Item transactions.  You affirm that you are aware and acknowledge that NFT Global Ltd., is a non-custodial service provider and has designed this Platform to be directly accessible by the Users without any involvement or actions taken by NFT Global Ltd., or any third-party.<br/><br/>

External Sites<br/>
The Platform or Site may include hyperlinks to other websites or resources (collectively, “External Sites”), which are provided solely as a convenience to our users.  We have no control over any External Sites.  You acknowledge and agree that we are not responsible for the availability of any External Sites, and that we do not endorse any advertising, products or other materials on or made available from any External Sites.  Furthermore, you acknowledge and agree that we are not liable for any loss or damage which may be incurred as a result of the availability or unavailability of the External Sites, or as a result of any reliance placed by you upon the completeness, accuracy or existence of any advertising, products or other materials on, or made available from, any External Sites.<br/><br/>

User Account and Security<br/>
User Agrees to Provide Accurate Registration Information<br/>
The User must provide accurate and complete registration information when you create an account for the Platform. By creating an account, you agree to provide accurate, current and complete account information about yourself, and to maintain and promptly update as necessary your account information.<br/><br/>

User is Responsible for Account Security<br/>
You are solely responsible for the security of your account and your MetaMask wallet (and other Ethereum wallets and accounts).  You agree to undertake to maintain at all times adequate security and control of all of your Account details, passwords, personal identification numbers or any other codes that you use to access the Platform or the Services.  You must ensure that Account(s) registered under your name will not be used by any other person. You must notify us immediately through email of any breach of security, loss, theft or unauthorized use of your username, password or security information.<br/><br/>

NFT Global Ltd., May Suspend Hacked Accounts<br/>
NFT Global Ltd., reserves the right to terminate, suspend or restrict your access to any Account(s) if there is reasonable suspicion by us that the person logged into your Account(s) is not you or if we suspect that the Account(s) have been or will be used for any illegal, fraudulent, or unauthorized purposes. Under no circumstances shall NFT Global Ltd., or indemnified persons in accordance with these Terms be responsible or liable for any direct or indirect losses (including loss of profits, business or opportunities), damages or costs suffered by you or any other person or entity due to any such termination, suspension or restriction of access to any Account(s).<br/><br/>

User May Not Use the Platform for Illegal Activity<br/>
You agree to use the Platform only for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations.  Without limitation, you may not, and may not allow any third party to: (i) send, upload, distribute or disseminate any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content; (ii) undertake any unlawful activity which would violate, or assist in violation of, any law, statute, ordinance, or regulation, sanctions program administered in any relevant country; (iii) distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; (iv) impersonate another person (via the use of an email address or otherwise); (v) upload, post, transmit or otherwise make available through the Platform any content that infringes the intellectual proprietary rights of any party; (vi) operate to defraud NFT Global Ltd., other users, or any other person or provide false, inaccurate or misleading information; (vii) use the Platform to violate the legal rights (such as rights of privacy and publicity) of others; (viii) engage in, promote, or encourage illegal activity (including, without limitation, terrorism, tax evasion or money laundering); (ix) interfere with another individual’s or entity’s access to or use of the Platform; defame, abuse, extort, harass, stalk, threaten or otherwise violate or infringe the legal rights (such as, but not limited to, rights or privacy, publicity and intellectual property) of others; incite, threaten, facilitate, promote, or encourage hate, racial intolerance or violent acts against others; harvest or otherwise collect information from the Platform about others, including without limitation email addresses, without proper consent; (x) exploit the Platform for any unauthorized commercial purpose; (xi) modify, adapt, translate, or reverse engineer any portion of the Platform; (xii) remove any copyright, trademark or other proprietary rights notices contained in or on the Platform or any part of it; (xiii) reformat or frame any portion of the Platform; (xiv) display any content on the Platform that contains any hate-related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third party rights; (xv) use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the Platform or the content posted on the Platform, or to collect information about its users for any unauthorized purpose; (xvi) create user accounts by automated means or under false or fraudulent pretenses; or (xvii) access or use the Platform for the purpose of creating a product or service that is competitive with any of our products or services.<br/><br/>

User Must Be of Age<br/>
You affirm that you are over the age of 18, as the Platform is not intended for children under 18. IF YOU ARE 13 OR OLDER BUT UNDER THE AGE OF 18, OR THE LEGAL AGE OF MAJORITY WHERE YOU RESIDE IF THAT JURISDICTION HAS AN OLDER AGE OF MAJORITY, THEN YOU AGREE TO REVIEW THESE TERMS WITH YOUR PARENT OR GUARDIAN TO MAKE SURE THAT BOTH YOU AND YOUR PARENT OR GUARDIAN UNDERSTAND AND AGREE TO THESE TERMS.  YOU AGREE TO HAVE YOUR PARENT OR GUARDIAN REVIEW AND ACCEPT THESE TERMS ON YOUR BEHALF. IF YOU ARE A PARENT OR GUARDIAN AGREEING TO THE TERMS FOR THE BENEFIT OF A CHILD OVER 13, THEN YOU AGREE TO AND ACCEPT FULL RESPONSIBILITY FOR THAT CHILD’S USE OF THE PLATFORM, INCLUDING ALL FINANCIAL CHARGES AND LEGAL LIABILITY THAT HE OR SHE MAY INCUR.<br/><br/>

SOBA Items<br/>
All Artwork (“Art”, “Work(s)”, “Artwork(s)”, or “Creation(s)”) on the SOBA Platform is represented by a unique cryptographic token exclusively Minted by one of SOBA’s approved Artists.  Each SOBA Item (“Item(s)”, “Token(s)”, “Non-fungible token(s)”, or “NFT(s)”) is Minted by an Artist using the SOBA Smart Contracts based on an Artist’s original Artwork.  SOBA Items are forever tracked and stored on the Ethereum blockchain, providing the Collector of a SOBA Item with a permanent record of authenticity and ownership.<br/><br/>

Creating SOBA Items<br/>
Only Artists invited and approved by SOBA are able to use the Platform to “Mint” and sell SOBA Items.  Artwork Minted and sold on the SOBA Marketplace includes, but is not limited to: visual works, audiovisual works, animations, audio, photographs, 3D works, GIFS, and other creative digital works.<br/><br/>

Applying to be a SOBA Artist<br/>
Artists seeking an invitation to create and list works for sale on the SOBA should email to apply for promotional drop. SOBA has unilateral discretion in curating its Artist Network and makes no guarantees or promises that any Artists will be approved, even if the Artist was invited by a member of the SOBA Team to submit the Request.<br/><br/>

Artist Whitelisting and Minting<br/>
Approved Artists are “Whitelisted” and granted permission to Mint SOBA Items using one or more of our Smart Contracts.  To create a SOBA Item, Approved Artists must upload an original digital Artwork, provide information about the artwork, authenticate the work, initiate a request to a token Minting Smart Contract and – voila – the Artist has Minted a unique, cryptographic token representing a digital version of the artwork.<br/><br/>

Artist Agrees to Mint only “Original” Works<br/>
By Minting a SOBA Item, Artists expressly represent and warrant that their Work is an original creation.  Artists are prohibited from Minting Works consisting of unlicensed or unauthorized copyrighted content, including any imagery, design, audio, video, human likeness, or other unoriginal content not created by the Artist, not authorized for use by the Artist, not in the public domain, or otherwise without a valid claim of fair use.  Artist can only mint works that they personally created and must refrain from minting works to which copyright ownership is unknown or disputed (i.e., commissioned works or “works made for hire”).<br/><br/>

SOBA Copyright Community Guidelines<br/>
Copyright is the law of art.  As a digital art platform, we take copyright law seriously and encourage our Artists and Collectors to learn more about their rights.<br/><br/>

Artists Must Have Authority to Mint, Display, and Sell the Work<br/>
Artist expressly represents and warrants that works Minted on the SOBA Platform contain only original artistic content otherwise authorized for use by the Artist.  To the extent a Work contains unoriginal content, including content from Works by other SOBA Artists, the Minting Artist further represents and warrants that it has permission to incorporate the unoriginal content.  Artist represents and warrants that the sale, display or performance of minted SOBA are Item on the Platform is not a violation of any agreement, contract, or obligation owed to a third-party.<br/><br/>

Artists May Be Removed from the Platform<br/>
Failure to abide by these Terms and/or the SOBA Guidelines may result in, without limitation, suspension or deletion of the Artist’s account, revocation of the Artist’s minting privileges and other permissions to the SOBA Smart Contracts or Platform, delisting the Artist’s items on the Site, or paying monetary damages.  SOBA has the unilateral authority and discretion to remove, suspend, or revoke Artists’ access to the SOBA Smart Contracts or any other aspect of the Platform.<br/><br/>

Artist Indemnifies and Releases SOBA<br/>
Artist hereby agrees to indemnify SOBA and be held liable for any claim against SOBA arising out of the Artist’s breach of these Terms.  Artist hereby releases and forever discharges SOBA from any damages or causes of action resulting from a sale of any of the Artist’s listed SOBA Items occurring after the Artist’s breach of these Terms.<br/><br/>

The SOBA Platform<br/>
The SOBA Platform facilitates a peer-to-peer digital art Marketplace and auction house where Artists, Collectors, and other Users can sell, purchase, list for auction, make offers, and bid on SOBA Items.  Collectors can obtain SOBA Items by making an offer accepted by the Artist, purchasing at an established List Price, or bidding on Items available in one of our revolutionary smart contract-enabled auctions.<br/><br/>

Purchasing SOBA Items with a List Price<br/>
SOBA Items are optionally offered for immediate acceptance at a List Price (in ETH) established by the Artist.  Collectors can purchase SOBA Items with a List Price through the Site by sending an equivalent amount of ETH to a Smart Contract configured to initiate a transfer of the SOBA Item, plus additional fees and gas.<br/><br/>

Making Offers on SOBA Items<br/>
Users can make offers on all listed SOBA Items through the Site.  Offers on the SOBA Marketplace are legally binding, revocable offers to purchase the Item capable of immediate acceptance by the Owner of the Item.  By making an offer, the Collector agrees to temporarily send and lose control over an amount of offered ETH to a Smart Contract.  The Smart Contract is configured to hold the offered ETH until either the offer is accepted by the Owner of the Item, a higher offer is received, or the offer is revoked.  The Owner of the Item has the unilateral authority to accept the bid.<br/><br/>

Users Agree to the Automated Collection and Disbursement of Fees by the Smart Contracts<br/>
The User agrees and understands that all fees, commissions, and royalties are transferred, processed, or initiated directly through one or more of the Smart Contracts on the Ethereum blockchain network.  By transacting on the platform and by using the Smart Contracts, the User hereby acknowledges, consents to, and accepts all automated fees, commissions, and royalties for the sale of Items on the SOBA Platform.  The User hereby consents to and agrees to be bound by the Smart Contracts’ execution and distribution of the fees, commissions, and royalties.    Users      hereby waive any entitlement to royalties, commissions, or fees paid to another by operation of the Smart Contracts.<br/><br/>

Users Consent to Automated Royalties to Artists<br/>
The User consents to the automated collection and disbursement to Artists of royalties for Secondary Market sales of SOBA Items.  The User hereby waives any first sale defense or argument with respect to Secondary Market activities resulting in a royalty to a SOBA Artist.<br/><br/>

SOBA Makes No Representations on Price or Value<br/>
Users acknowledge and consent to the risk that the price of an Item purchased on the SOBA marketplace may have been influenced by User activity outside of the control of NFT Global Ltd., or the SOBA Platform. SOBA does not represent, guarantee, or warrant the accuracy or fairness of the price of any SOBA. Item sold or offered for sale on or off of the Marketplace.  The User agrees and acknowledges that SOBA is not a fiduciary nor owes any duties to any User of the platform, including the duty to ensure fair pricing of SOBA Items or to police User behavior on the Marketplace.<br/><br/>

Off Market Transactions<br/>
SOBA does not generally collect any fees, commissions, or royalties for transactions occurring outside of the SOBA Marketplace and not involving the SOBA Smart Contracts.  To support the SOBA Artists and the Platform, we encourage Collectors to list Items for sale on the SOBA Site, however Collectors are permitted to sell or transfer their Items on third party exchanges.  The Artist and all other Users hereby waive any entitlement to royalties, commissions, or fees for off market transactions.  The User irrevocably releases, acquits, and forever discharges NFT Global Ltd., and its subsidiaries, affiliates, officers, and successors of any liability for royalties, fines, or fees not received by the User from any off-market transaction.<br/><br/>

Gas<br/>
All User transactions on the SOBA Platform, including without limitation Minting, tokenizing, bidding, listing, offering, purchasing, or confirming, are facilitated by Smart Contracts existing on the Ethereum network.  The Ethereum network requires the payment of a transaction fee (a “Gas fee”) for every transaction that occurs on the Ethereum network, and thus every transaction occurring on the SOBA Platform.  The value of the Gas Fee changes, often unpredictably, and is entirely outside of the control of NFT Global Ltd., or the SOBA Platform.  The User acknowledges that under no circumstances will a contract, agreement, offer, sale, bid, or other transaction on the Platform be invalidated, revocable, retractable, or otherwise unenforceable on the basis that the Gas Fee for the given transaction was unknown, too high, or otherwise unacceptable to a User. Users also acknowledge and agree that gas is non-refundable under all circumstances.<br/><br/>

Taxes<br/>
Users are responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments now or hereafter claimed or imposed by any governmental authority, “ associated with your use of the Platform (including, without limitation, any taxes that may become payable as the result of your ownership, transfer, purchase, sale, or creation of any artworks).<br/><br/>

Transactions Executed by Smart Contracts<br/>
To initiate a transaction on the SOBA Site, a User must voluntarily invoke one or more Smart Contract operations from an Ethereum Wallet. All transactions on the SOBA Site, including but not limited to transfers, offers, bids, listings, sales, or purchases of SOBA Items are initiated though one or more Smart Contracts at the sole discretion and at the complete risk of the Users.  The Smart Contracts are configured to facilitate the execution of a voluntary User offer, an acceptance of an offer, or other confirmation to purchase, sell, bid on, list, or transfer a SOBA Item.  The User acknowledges the risk of Smart Contracts and agrees to be bound by the outcome of any Smart Contract operation by invoking, calling, requesting, or otherwise engaging with the Smart Contract, whether or not the Smart Contract behaves as the User expects.<br/><br/>

User Acknowledges the Risk of Smart Contracts and Blockchain Technology<br/>
SOBA Site transactions, including but not limited to primary sales, secondary market sales, listings, offers, bids, acceptances, and other operations through the Site utilize experimental smart contract and blockchain technology, including non-fungible tokens, cryptocurrencies, consensus algorithms, and decentralized or peer-to-peer networks and systems. Users acknowledge and agree that such technologies are experimental, speculative, and inherently risky. Users acknowledge and agree that the SOBA smart contracts may be subject to bugs, malfunctions, timing errors, hacking and theft, or changes to the protocol rules of the Ethereum blockchain (i.e., "forks"), which can adversely affect the smart contracts and may expose you to a risk of total loss, forfeiture of your digital currency or SOBA Items, or lost opportunities to buy or sell SOBA Items. SOBA assumes no liability or responsibility for any such smart contract or related failures, risks, or uncertainties.<br/><br/>

Users Assume the Risk of Interacting with on Smart Contracts<br/>
Users hereby acknowledge and assume the risk of initiating, interacting with, participating in Marketplace or Auction transactions and take full responsibility and liability for the outcome of any transaction they initiate, whether or not the smart contracts, the SOBA Site, or other market participants behave as expected or intended. Users hereby represent that they are knowledgeable, experienced and sophisticated in using blockchain technology, the SOBA site, and in initiating Ethereum-based transactions.<br/><br/>

No Attacking or Interfering with the Smart Contracts<br/>
Users are forbidden from engaging in any attack, hack, denial-of-service attack, interference, or exploit of any SOBA smart contract. Operations performed by a User that are technically permitted by a SOBA smart contract may nevertheless be a violation of our Terms of Service and the law.<br/><br/>

SOBA Makes No Representations or Warranties<br/>
SOBA makes no representations or warranties, express or implied, written or oral, made by or on behalf of SOBA in connection therewith, including any representations or warranties of title, non-infringement, functionality, merchantability, usage, security, suitability or fitness for any particular purpose, workmanship or technical quality of any SOBA Item or work, smart contract code, or software.<br/><br/>

SOBA is Not Liable for the Outcome of Any Site Transaction<br/>
SOBA shall not be liable to you for contract, tort, or any other types of damages, including indirect, special, incidental, consequential, punitive or exemplary damages arising out of or related to participation in or the outcome of a Marketplace transaction, whether or not SOBA has been advised or knew of the possibility of such damages. SOBA’s liability for damages under this Agreement shall in all cases be limited to, and under no circumstances shall exceed, the amount of proceeds actually received by SOBA arising out of the damage after deducting all costs, fees and liabilities incurred by or on behalf of SOBA.<br/><br/>

SOBA May Modify these Terms and the Smart Contracts<br/>
SOBA reserves, the right, in its sole and absolute discretion, to amend, modify, alter or supplement these Terms and the smart contracts accessible through the SOBA Site from time to time.<br/><br/>

The Marketplace Smart Contracts Are Not Controlled By NFT Global Ltd.,<br/>
All Marketplace transactions are executed by one or more Smart Contracts processed on the Ethereum Virtual Machine and not under any direct control by NFT Global Ltd., or any other third party. The User acknowledges and agrees that NFT Global Ltd., is not a party to any agreement or transaction between any Users involving the purchase, offer, sale, auction, or transfer of SOBA Items, whether or not a commission or fee is received by SOBA as a consequence of the transaction. Items listed for sale on the SOBA Marketplace are not offered on consignment or held in trust on behalf of any Artist, Collector, Owner, or User.  NFT Global Ltd., reserves the right to execute Smart Contract transactions on the SOBA Marketplace as a collector of SOBA items.<br/><br/>

SOBA SITE<br/>
The SOBA Site is a transparent and open digital collectibles that depends on the honest participation of all Users.<br/><br/>

Users are Prohibited from Manipulating the Prices<br/>
Users are expressly forbidden from accepting, soliciting, offering, bidding, engaging with the Smart Contracts, or otherwise transacting on or off of the SOBA Platform with the intent to artificially devalue, inflate, or otherwise deceptively influence, misrepresent, or cause to be misrepresented the price a SOBA Item, groups of SOBA Items, or SOBA Items created by particular Artists.<br/><br/>

Users are Prohibited from Using the Site<br/>
Users are expressly forbidden from selling works, listing items for sales, making purchase during the sales, purchasing a work, or engaging in any other site transaction for the purpose of concealing economic activity, laundering money, or financing terrorism. For example, and without limitation, Users are forbidden from using the Platform and any Smart Contract to conceal or transfer proceeds or assets relating to criminal activity or to pay for a Item for any other reason than to obtain the Item. All Users expressly represent and warrant by performing transaction involving the SOBA Site or Smart Contracts that their actions are legal under United States law and the jurisdiction from which they initiate the transaction.<br/><br/>

Users Agree to Report Suspicious Market Activity<br/>
Users agree to report suspicious market activity of other SOBA Users.  If a User suspects that one or more SOBA Users are in violation of these Terms, the User should promptly inform the SOBA team.<br/><br/>

Violation of the Code of Conduct May Result in SOBA Intervention<br/>
The User hereby agrees and acknowledges that any forbidden Marketplace conduct described herein and in the may be a violation of federal or state law and/or these Terms.  SOBA hereby reserves the right to completely or partially restrict or revoke a User’s access to the Site for violating these Terms. SOBA reserves the right to amend, rectify, edit, or otherwise alter SOBA Market transaction data to mitigate market harm caused by a User’s violation of these terms.<br/><br/>

User Releases SOBA from Claims Arising From Other Users’ Violations of these Terms<br/>
The User irrevocably releases, acquits, and forever discharges NFT Global Ltd., and its subsidiaries, affiliates, officers, and successors for and against any and all past or future causes of action, suits, or controversies arising out of another User’s violation of the these Terms.<br/><br/>

Ownership<br/>
All works Minted on the Platform are subject to the SOBA License, the terms of which are described below.  All Users who receive a SOBA Item acknowledge and agree to accept or purchase the Item subject to the conditions of the License.<br/><br/>

Ownership of a SOBA Item<br/>
Owning a SOBA Item is similar to owning a piece of physical art.  You own a cryptographic token representing the Artist’s creative Work as a piece of property, but you do not own the creative Work itself.  Collectors may show off their ownership of collected SOBA Items by displaying and sharing the Underlying Artwork, but Collectors do not have any legal ownership, right, or title to any copyrights, trademarks, or other intellectual property rights to the underlying Artwork, excepting the limited license granted by these Terms to Underlying Artwork.  The Artist reserves all exclusive copyrights to Artworks underlying SOBA Items Minted by the Artist on the Platform, including but not limited to the right to reproduce, to prepare derivative works, to display, to perform, and to distribute the Artworks.<br/><br/>

The Collector’s Limited License to a Minted Artwork<br/>
Owning a SOBA Item is also different than owning a piece of physical art.  Art on the SOBA Platform is digital, meaning that it is inherently easier to share, display, replicate, and distribute around cyberspace.  Collectors may not infringe on any of the exclusive rights of the copyright holder (i.e., the Artist). By Minting Items on the Platform, Artist affirmatively grants a limited, worldwide, non-assignable, non-sublicensable, royalty-free license to display the Artwork underlying SOBA  Items legally owned and properly obtained by the Collector.<br/><br/>

Collectors May Display the Artwork<br/>
The Collector’s limited license to display the Work, or perform the Work in the case of audiovisual works, includes, but is not limited to, the right to display or perform the Work privately or publicly: (i) for the purpose of promoting or sharing the Collector’s purchase, ownership, or interest in the Work, for example, on social media platforms, blogs, digital galleries, or other Internet-based media platforms; (ii) for the purpose of sharing, promoting, discussing, or commenting on the Work; (iii) on third party Marketplaces, exchanges, Platforms, or applications in association with an offer to sell, or trade, the Token associated with Work; and (iv) within decentralized virtual environments, virtual worlds, virtual galleries, virtual museums, or other navigable and perceivable virtual environments, including simultaneous display of multiple copies of the Work within one or more virtual environments.<br/><br/>

Other Restrictions on the Collector’s Limited License<br/>
The Collector agrees that it may not, nor permit any third party, to do or attempt to do any of the foregoing without the Artist’s express prior written consent in each case: (i) modify, distort, mutilate, or perform any other modification to the Work which would be prejudicial to the Artist’s honor or reputation; (ii) use the Work to advertise, market, or sell any third party product or service; (iii) use the Work in connection with images, videos, or other forms of media that depict hatred, intolerance, violence, cruelty, or anything else that could reasonably be found to constitute hate speech or otherwise infringe upon the rights of others; (iv) incorporate the Work in movies, videos, video games, or any other forms of media for a commercial purpose, except to the limited extent that such use is expressly permitted by these Terms or solely for your Collector’s personal, non-commercial use; (v) sell, distribute for commercial gain, or otherwise commercialize merchandise that includes, contains, or consists of the Work; (vi) attempt to trademark, copyright, or otherwise acquire additional intellectual property rights in or to the Work; (vii) attempt to Mint, tokenize, or create an additional cryptographic token representing the same Work, whether on or off of the SOBA Platform; (viii) falsify, misrepresent, or conceal the authorship of the Work or the SOBA Item; or (ix) otherwise utilize the Work for the Collector’s or any third party’s commercial benefit.<br/><br/>

The Limited License Belongs Only to the Current Owner of a SOBA Item<br/>
The User agrees and acknowledges that the lawful ownership, possession, and title to a SOBA Item is a necessary and sufficient condition precedent to receive the limited license rights to the underlying Work provided by these Terms.  Any subsequent transfer, dispossession, burning, or other relinquishment of a SOBA Item will immediately terminate the former Owner’s rights and interest in the license or SOBA Item as provided by these Terms.<br/><br/>

The Artist’s Rights and Restrictions<br/>
The Artist owns all legal right, title, and interest in all intellectual property rights to creative Works underlying SOBA Items Minted by the Artist on the Platform, including but not limited to copyrights and trademarks.  As the copyright owner, the Artist enjoys several exclusive rights to the Work, including the right to reproduce, the right to prepare derivative works, the right to distribute, and the right to display or perform the Art.  Subject to, and in accordance with these Terms, the Artist hereby acknowledges, understands, and agrees that Minting a Work on the Platform constitutes an express and affirmative grant of the limited license rights to the Work to all subsequent Owners of the SOBA Item, as provided herein.<br/><br/>

Artist Grants SOBA a License to All Minted Works<br/>
The Artist hereby acknowledges, understands, and agrees that Minting a Work on the Platform constitutes an express and affirmative grant to NFT Global Ltd., its affiliates and successors a non-exclusive, world-wide, assignable, sublicensable, perpetual, and royalty-free license to make copies of, display, perform, reproduce, and distribute the Work on any media whether now known or later discovered for the broad purpose of operating, promoting, sharing, developing, marketing, and advertising the Platform, the Site, the Marketplace, or any other purpose related to the SOBA Platform or business, including without limitation, the express right to: (i) display or perform the Work on the Site, a third party platform, social media posts, blogs, editorials, advertising, market reports, virtual galleries, museums, virtual environments, editorials, or to the public; (ii) create and distribute digital or physical derivative works based on the Work, including without limitation, compilations, collective works, and anthologies; (iii) indexing the Work in electronic databases, indexes, catalogues, the Smart Contracts, or ledgers; and (iv) hosting, storing, distributing, and reproducing one or more copies of the Work within a distributed file keeping system, node cluster, or other database (e.g., IPFS) or causing, directing, or soliciting others to do so.<br/><br/>

User Releases SOBA from Copyright Claims<br/>
The Artist and all Users irrevocably release, acquit, and forever discharge NFT Global Ltd., and its subsidiaries, affiliates, officers, and successors of any liability for direct or indirect copyright or trademark infringement for NFT Global Ltd.’s use of a Work in accordance with these Terms, including without limitation, NFT Global Ltd.’s solicitation, encouragement, or request for Users or third parties to host the Work for the purpose of operating a distributed database and NFT Global Ltd.’s deployment or distribution of a reward, a token, or other digital asset to Users or third parties for hosting Works on a distributed database.<br/><br/>

Copyright Infringement Complaints Under the Digital Millennium Copyright Act<br/>
NFT Global Ltd., respects the intellectual property rights of others. It is our policy to respond promptly any claim that Content posted on the Site infringes the copyright or other intellectual property rights of any person. NFT Global Ltd., will use reasonable efforts to investigate notices of alleged infringement and will take appropriate action under the Digital Millennium Copyright Act (DMCA) and these Terms, including removing or disabling access to Content claimed to be infringing and/or terminating accounts and access to the Site.<br/><br/>

The DMCA provides a process for a copyright owner to give notification to an online service provider concerning alleged copyright infringement. When an effective DMCA notification is received, the online service provider responds under this process by taking down the offending content. On taking down content under the DMCA, we will take reasonable steps to contact the Artist responsible for minting the removed content so that a Counternotification may be filed if applicable. On receiving a valid Counternotification, we generally restore the content in question, unless we receive notice from the DMCA Notice provider that a legal action has been filed seeking a court order to restrain the alleged infringer from engaging in the infringing activity. Our Privacy Policy does not protect any information contained in any DMCA Take-Down Notice or Counternotification. If you have any questions about your rights, copyright infringement, or the notification and counter-notification process under the Digital Millennium Copyright Act (the “DMCA”), we recommend that you speak with an attorney.<br/><br/>

Filing a DMCA “Take Down” Notification<br/>
If you are a copyright owner or an agent thereof and believe that any Content on the SOBA Site infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our designated DMCA agent with the following information in writing (see 17 U.S.C. § 512 for further detail):<br/>
1. A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br/>
2. Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works, a representative list of such works at that site.<br/>
3. Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material. *Providing URLs in the body of your DMCA notification is the best way to help us locate content quickly<br/>
4. Information reasonably sufficient to permit us to contact you (the complaining party), such as an address, telephone number, and an electronic mail address at which you (the complaining party) may be contacted.<br/>
5. A statement that you (the complaining party) have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.<br/>
6. A statement that the information in the notification is accurate, and under penalty of perjury, that you (the complaining party) are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br/>
7. **(Optional) Provide information, if possible, sufficient to permit us to notify the user(s) who posted the content that allegedly contains infringing material.<br/>
Any person who knowingly materially misrepresents that Content or an activity is infringing or that any material or activity was removed or disabled by mistake or misidentification, shall be liable to us and possibly others for any damages, including costs and attorneys’ fees incurred by us in removing or disabling access to the material or activity claimed to be infringing or in replacing the removed material or enabling access to it.<br/><br/>

Responding to an DMCA Notice with a Counter Notification<br/>
We will take reasonable steps to promptly inform you if your content has been taken down upon receipt of an effective DMCA Infringement Take Down Notification. If you believe that the content that was removed or to which access was disabled is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to mint and use the material, you may send a Counter Notification containing the following information to our Designated Agent.<br/>
1. Your physical or electronic signature;<br/>
2. Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled;<br/>
3. A statement that you have a good faith belief that the material was removed or disabled as a result of mistake or a misidentification of the material; and<br/>
4. Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the U.S. district court in the state in which you reside (or the U.S. district court where our headquarters are located if your address is outside of the United States), and a statement that you will accept service of process from the person who provided notification of the alleged infringement to us.<br/>
You have ten (10) business days after receipt of a DMCA take-down Notice to send us an effective Counter Notification or the allegedly infringing material may not be restored.<br/>
Any person who knowingly materially misrepresents that material or an activity is infringing or that any material or activity was removed or disabled by mistake or misidentification, shall be liable to us for any damages, including costs and attorneys’ fees incurred by us in removing or disabling access to the material or activity claimed to be infringing or in replacing the removed material or enabling access to it.<br/><br/>

Contacting NFT Global Ltd., Designated Agent<br/>
You must submit your DMCA Take-Down Notices and Counternotifications to our designated DMCA Agent by email.<br/><br/>

NFT Global Ltd., Has the Right to Remove Allegedly Infringing Content<br/>
NFT Global Ltd., reserves the right to remove any Content that allegedly infringes another person's copyright or trademark rights, thereby restricting access to or visibility of the Work on the Site and restricting the Owner's ability to sell, access, or view the Work on the Marketplace. All transactions involving SOBA Items are conducted with the knowledge and assumption of the risk that the Item may subsequently be removed from the SOBA Site and Marketplace as a consequence of a DMCA dispute or a User’s violation of these Terms. SOBA shall not be liable to a Collector or Artist of an Item that was subsequently taken down by SOBA pursuant to a valid DMCA Take-Down Notice or a determination of a User’s violation of these Terms.<br/><br/>

NFT Global Ltd., Has the Right to Terminate Repeat Infringers’ Accounts<br/>
NFT Global Ltd., implements a strict “repeat infringer” policy, which requires it to terminate a User’s access to the Site and Smart Contracts, including restricting minting privileges and terminating a User’s account if, under appropriate circumstances, the User is determined to be a repeat infringer. NFT Global Ltd., also reserves the right to restrict an Artist’s account for reasons other than copyright infringement, such as, but not limited to, minting pornographic, obscene, or hateful content, or excessive or suspicious minting conduct. We may at any time, without prior notice and in our sole discretion, remove such material and/or terminate a User’s account for submitting such material in violation of our Terms of Service.<br/><br/>

Infringers May Be Liable to Collectors and SOBA<br/>
Artists expressly agree to refund to the Collector and/or SOBA the entire portion of ether (ETH) received from the sale of a SOBA Item that was subsequently removed from the Site pursuant to an effective DMCA request to which the Artist failed to timely submit an effective DMCA Counternotification. SOBA, under any circumstance, will not be held liable to any Collector or User for removing allegedly infringing works from the Platform or otherwise fulfilling its legal obligations under the DMCA.<br/><br/>

User Agree to Cooperate with SOBA<br/>
Artist, Collectors, and all Users expressly agree to cooperate and timely respond to SOBA’s investigations, requests, and inquiries related to DMCA disputes or allegations of infringement. Users agree to initiate a “burn” transaction upon SOBA’s request for Works that have been permanently removed from the SOBA Site pursuant to a valid DMCA Take-Down Notice, or that are otherwise alleged to be infringing.<br/><br/>

Disclaimers and Limitations on Our Liability<br/>
TO THE EXTENT PERMITTED BY APPLICABLE LAW, NFT GLOBAL LTD., AND ITS OFFICERS, EMPLOYEES, DIRECTORS, SHAREHOLDERS, PARENTS, SUBSIDIARIES, AFFILIATES, AGENTS, AND LICENSORS  DISCLAIM ALL WARRANTIES, CONDITIONS, AND REPRESENTATIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING THOSE RELATED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND THOSE ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.<br/><br/>

NFT Global Ltd., Makes No Representations or Warranties<br/>
TO THE EXTENT PERMITTED BY APPLICABLE LAW, NFT GLOBAL LTD., AND ITS AFFILIATES MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT THE ACCURACY OR COMPLETENESS OF CONTENT AVAILABLE ON OR THROUGH THE SITE OR ABOUT PRODUCTS, THE VALUE OR TITLE OF SOBA ITEMS, OR THE CONTENT OF ANY THIRD-PARTY WEBSITES OR SERVICES LINKED TO OR INTEGRATED WITH OUR SITE. NFT GLOBAL LTD. AND ITS AFFILIATES WILL HAVE NO LIABILITY FOR ANY: (A) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (B) PERSONAL INJURY OR PROPERTY DAMAGE RESULTING FROM YOUR ACCESS TO OR USE OF THE SITE OR CONSUMPTION OF ANY PRODUCTS; (C) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS OR OF ANY PERSONAL INFORMATION OR USER DATA; (D) ANY INTERRUPTION OF TRANSMISSION TO OR FROM THE SITE; (E) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED ON OR THROUGH THE SITE OR SERVICES BY ANY THIRD PARTY; (F) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED OR SHARED THROUGH THE SITE OR SERVICES; OR (G) LOSS OR DAMAGED CAUSED BY ANOTHER USER’S VIOLATION OF THESE TERMS.<br/>
TO THE EXTENT PERMITTED BY LAW, OUR COMPANY AND ITS AFFILIATES WILL NOT BE RESPONSIBLE FOR LOST PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.<br/><br/>

Limitation on Liability<br/>
TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF OUR COMPANY AND ITS AFFILIATES, FOR ANY CLAIMS UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE TOTAL AMOUNT YOU PAID TO US IN FEES OVER THE PAST TWELVE (12) MONTHS.<br/>
Some jurisdictions do not allow the exclusion of certain warranties and limitations of liability provided in this Section.  If you are in such a jurisdiction, some of the above limitations and disclaimers may not apply to you.  To the extent we may not, as a matter of applicable law, disclaim any implied warranty or limit our liabilities, the scope and duration of such warranty and the extent of our liability will be the minimum permitted by applicable law.<br/><br/>

Assumption of the Risk<br/><br/>

User Acknowledges the Risk of Cryptocurrency and Smart Contracts<br/>
YOU FURTHER REPRESENT AND WARRANT THAT YOU UNDERSTAND AND ARE WILLING TO ACCEPT THE RISKS ASSOCIATED WITH CRYPTOGRAPHIC SYSTEMS SUCH AS THE SMART CONTRACTS, THE ETHEREUM BLOCKCHAIN, NON-FUNGIBLE TOKENS, AND THE INTERPLANETARY FILE SYSTEM.<br/>
WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF THE ETHEREUM NETWORK OR THE METAMASK ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (A) USER ERROR, SUCH AS FORGOTTEN PASSWORDS OR INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) UNAUTHORIZED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING BUT NOT LIMITED TO THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE PLATFORM, ETHEREUM NETWORK, THE METAMASK ELECTRONIC WALLET OR ETHEREUM-COMPATIBLE BROWSER OR WALLET.<br/><br/>

NFT Global Ltd., is Not Responsible for Technical Errors on the Ethereum Blockchain<br/>
NFT GLOBAL LTD., IS NOT RESPONSIBLE FOR LOSSES DUE TO BLOCKCHAINS OR ANY OTHER FEATURES OF THE ETHEREUM NETWORK OR THE METAMASK ELECTRONIC WALLET OR ANY ETHEREUM-COMPATIBLE BROWSER OR WALLET, INCLUDING BUT NOT LIMITED TO LATE REPORT BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN SUPPORTING THE ETHEREUM NETWORK, INCLUDING FORKS, TECHNICAL NODE ISSUES, OR ANY OTHER ISSUES HAVING FUND LOSSES AS A RESULT.<br/>
Upgrades by Ethereum to the Ethereum platform, a hard fork in the Ethereum platform, or a change in how transactions are confirmed on the Ethereum platform may have unintended, adverse effects on all blockchains using the ERC-20 or ERC-721 standards, including the SOBA ecosystem.<br/><br/>

The User Acknowledges the Risks of the Platform<br/>
You acknowledge that the Platform is subject to flaws and acknowledge that you are solely responsible for evaluating any code provided by the Platform. This warning and others provided in this Agreement by NFT Global Ltd., in no way evidence or represent an ongoing duty to alert you to all of the potential risks of utilizing or accessing the Platform. The Platform may experience sophisticated cyber-attacks, unexpected surges in activity or other operational or technical difficulties that may cause interruptions to or delays on the Platform.  You agree to accept the risk of the Platform failure resulting from unanticipated or heightened technical difficulties, including those resulting from sophisticated attacks, and you agree not to hold us accountable for any related losses.  We will not bear any liability, whatsoever, for any damage or interruptions caused by any viruses that may affect your computer or other equipment, or any phishing, spoofing or other attack.<br/><br/>

NFT Global Ltd.,  Does Not Guarantee the Value or Title of SOBA Items<br/>
The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the value of your SOBA Items, which may also be subject to significant price volatility. A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of the SOBA ecosystem, and therefore the potential utility or value of SOBA Items.  The Platform, ETH and digital assets could be impacted by one or more regulatory inquiries regulatory actions, or legislative policies which could impede or limit the ability of NFT Global Ltd., to continue to develop the SOBA Platform, or which could impede or limit your ability to access or use the Platform or Ethereum blockchain. Sup SOBA Items may be encumbered by actual or possible copyright or trademark claims against the Item.<br/><br/>

User Acknowledges Financial Risk of Digital Assets<br/>
Use of the Platform, including the creating, buying or selling trading digital assets, may carry financial risk. digital assets are, by their nature, highly experimental, risky, volatile and transactions carried through the Platform are irreversible, final and there are no refunds.  You acknowledge and agree that you will access and use the Platform at your own risk.  The risk of loss in trading digital assets can be substantial.  You should, therefore, carefully consider whether such creating, buying or selling digital assets is suitable for you in light of your circumstances and financial resources. By using the Platform, you represent that you have been, are and will be solely responsible for making your own independent appraisal and investigations into the risks of a given transaction and the underlying digital assets. You represent that you have sufficient knowledge, market sophistication, professional advice and experience to make your own evaluation of the merits and risks of any transaction conducted via the Platform or any underlying digital asset. You accept all consequences of using the Platform, including the risk that you may lose access to your digital assets indefinitely.  All transaction decisions are made solely by you.  Notwithstanding anything in this Agreement, we accept no responsibility whatsoever for and will in no circumstances be liable to you in connection with use of the Platform for performing digital asset transactions. Under no circumstances will the operation of all or any portion of the Platform be deemed to create a relationship that includes the provision or tendering of investment advice.<br/><br/>

You Agree to Waive a Jury Trial<br/>
The parties agree that the arbitration will be kept confidential and that the existence of the proceeding and any element of it (including, without limitation, any pleadings, briefs or other documents submitted or exchanged and any testimony or other oral submissions and awards) will not be disclosed beyond the arbitration proceedings, except as may lawfully be required in judicial proceedings relating to the arbitration or by applicable disclosure rules and regulations of securities, regulatory authorities, or other governmental agencies.<br/>
This arbitration agreement does not preclude you or NFT Global Ltd., from seeking action by federal, state, or local government agencies.  You and NFT Global Ltd., may also bring qualifying claims in small claims court.  In addition, you and NFT Global Ltd., retain the right to apply to any court of competent jurisdiction for provisional relief, including pre-arbitral attachments or preliminary injunctions, and any such request shall not be deemed incompatible with these Terms, nor a waiver of the right to have disputes submitted to arbitration as provided in these Terms.<br/><br/>

Arbitration Costs<br/>
If you demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, NFT Global Ltd., will pay as much of the administrative costs and arbitrator fees required for the arbitration as the arbitrator deems necessary to prevent the cost of the arbitration from being prohibitive.  In the final award, the arbitrator may apportion the costs of arbitration and the compensation of the arbitrator among the parties in such amounts as the arbitrator deems appropriate.<br/><br/>

Class Action Waiver<br/>
YOU MAY NOT ACT AS A CLASS REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL, NOR PARTICIPATE AS A CLASS MEMBER OF ANY CLASS CLAIMANTS WITH RESPECT TO ANY CLAIM. CLAIMS MAY NOT BE ARBITRATED ON A CLASS OR REPRESENTATIVE BASIS.  You may only bring individual claims, and the arbitrator may only decide individual claims.  The arbitrator may not consolidate or join the claims of other persons or parties who may be similarly situated.<br/><br/>

Miscellaneous Terms<br/><br/>

These Terms May Change<br/>
These Terms may be discretionarily modified or replaced at any time, unless stated otherwise herein. The most current version of this Agreement will be posted on the Site with the “Last Revised” date at the top of the Agreement changed. Any changes or modifications will be effective immediately upon posting the revisions to the Site. You shall be responsible for reviewing and becoming familiar with any such modifications. You waive any right you may have to receive specific notice of such changes or modifications. Use of the Platform by you after any modification to the Agreement constitutes your acceptance of the Agreement as modified. If you do not agree to the Agreement in effect when you access or use the Platform, you Platform. We may, at any time and without liability or prior notice, modify or discontinue all or part of the Platform (including access to the Platform via any third-party links).<br/><br/>

The Smart Contracts May Change<br/>
The User acknowledges that NFT Global Ltd., may modify, change, amend, or replace one or more of the Smart Contracts from time to time.  The User agrees that a modification to one or more of the Smart Contracts does not alter any right or obligation conferred by these Terms.<br/><br/>

Confidentiality of Certain Communications<br/>
Users may voluntarily contact SOBA to report serious misuses of the SOBA Platform including, for example, suspicious market activity, hate speech, or other serious violations of these Terms.  User agrees to keep confidential all private correspondence with any members of the SOBA Team pertaining to another member’s alleged violation of these Terms or other inquiries about SOBA’s policies.<br/><br/>

Indemnification<br/>
You agree to indemnify and hold harmless our company and its affiliates from and against any and all claims, costs, proceedings, demands, losses, damages, and expenses (including, without limitation, reasonable attorney’s fees and legal costs) of any kind or nature, arising from or relating to, any actual or alleged breach of these Terms by you, a co-conspirator, or anyone using your account.  If we assume the defense of such a matter, you will reasonably cooperate with us in such defense.<br/><br/>

Severability<br/>
If any provision of these Terms is found to be unlawful or unenforceable, then that provision will be deemed severable from these Terms and will not affect the enforceability of any other provisions.<br/><br/>

Termination<br/>
You may terminate these Terms at any time by canceling your account on the Platform and discontinuing your access to and use of the Platform.  You will not receive any refunds if you cancel your account, or otherwise terminate these Terms.  You agree that we, in our sole discretion and for any or no reason, may terminate these Terms and suspend and/or terminate your account(s) for the Platform. You agree that any suspension or termination of your access to the Platform may be without prior notice, and that we will not be liable to you or to any third party for any such suspension or termination. If we terminate these Terms or suspend or terminate your access to or use of the Platform due to your breach of these Terms or any suspected fraudulent, abusive, or illegal activity, then termination of these Terms will be in addition to any other remedies we may have at law or in equity. Upon any termination or expiration of these Terms, whether by you or us, you may no longer have access to information that you have posted on the Platform or that is related to your account, and you acknowledge that we will have no obligation to maintain any such information in our databases or to forward any such information to you or to any third party.<br/><br/>

No Assignment of the Terms<br/>
Neither party may assign or transfer any rights or obligations under this Agreement without the prior written consent of the other party, provided that NFT Global Ltd.,, may assign this Agreement without your prior consent to any of NFT Global Ltd.’s affiliates, or to its successors in interest of any business associated with the services provided by NFT Global Ltd. This Agreement shall be binding upon the permitted assigns or transferees of each party.<br/><br/>

Governing Law and Jurisdiction<br/>
These Terms will be governed by and construed under the laws of the State of New York, without giving effect to any conflict of laws rules or provisions.  You agree that any action of whatever nature arising from or relating to these Terms, the Site, or our Products will be filed only in the state or federal courts in New York, New York.  You consent and submit to the personal jurisdiction of such courts for any such action.  The failure by us to enforce any right or provision of these Terms will not prevent us from enforcing such right or provision in the future.  We may assign our rights and obligations under these Terms, including in connection with a merger, acquisition, sale of assets or equity, or by operation of law.<br/><br/>

Please print a copy of these Terms for you records and PLEASE check the Site frequently for any changes to these Terms.<br/><br/>

            </p>
          </div>
        </div>
      </div>
      
      
      
    );
  }
}

export default Term;
